### ISSUE TITLE
Assertion Error when replicating this code with Google Colab

### ISSUE THREAD

**Issue by kenan-joot** [WillBrennan/SemanticSegmentation#10]
I get the following error code as I'm attempting to replicate this code on Google Colab, because I don't have a GPU on my local machine. I also get an assertion error when running on my local machine after altering the cuda code to tolerate a CPU. 

I've never worked with git lfs before, so I'm assuming the problem might be there, but I'm wondering if others may be having the same issue. 

Screenshot of my colab code attached

`INFO:root:loading FCNResNet101 from pretrained/model_segmentation_skin_30.pth`
`INFO:root:creating model with categories: ['skin']`
`/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py:550: UserWarning: Setting attributes on ParameterDict is not supported.`
  `warnings.warn("Setting attributes on ParameterDict is not supported.")`
`Downloading: "https://download.pytorch.org/models/resnet101-5d3b4d8f.pth" to /root/.cache/torch/hub/checkpoints/resnet101-5d3b4d8f.pth`
`100% 170M/170M [00:03<00:00, 44.7MB/s]`
`Downloading: "https://download.pytorch.org/models/fcn_resnet101_coco-7ecb50ca.pth" to /root/.cache/torch/hub/checkpoints/fcn_resnet101_coco-7ecb50ca.pth`
`100% 208M/208M [00:06<00:00, 33.3MB/s]`
`INFO:root:evaluating images from /root/Pictures/`
`Traceback (most recent call last):`
  `File "evaluate_images.py", line 72, in <module>
    for image_file in find_files(image_dir, ['.png', '.jpg', '.jpeg']):`
  `File "evaluate_images.py", line 31, in find_files
    assert dir_path.exists()`
`AssertionError`

![image](https://user-images.githubusercontent.com/69269687/104972238-5f1f4b00-59ae-11eb-94cd-9c3674407658.png)

**Comment by jajas** [comment]
@kenan-joot, look like there is no image in "~/Pictures" or not exit; one way to solution is to create a directory in colab and put some image there. Let me know it it works, pls!!!

**Comment by WillBrennan** [comment]
Definitely just `~/Pictures` not being a valid directory. Closing issue. 

@kenan-joot - There's an example in google colab in [issue 4](https://github.com/WillBrennan/SemanticSegmentation/issues/4)
