### ISSUE TITLE
pickle.UnpicklingError: invalid load key, 'v'.

### ISSUE THREAD

**Issue by TomChow01** [WillBrennan/SemanticSegmentation#11]
I keep getting pickle.UnpicklingError: invalid load key, 'v'. error when I'm trying to run the evaluate_images.py

**Comment by TomChow01** [comment]
** Here are the details:**


(semantic_segmentation) C:\Users\raghaver\Desktop\tamal\Codes\SemanticSegmentation-master>python evaluate_images.py --images ~/SampleImages/ --model pretrained/model_segmentation_skin_30.pth --model-type FCNResNet101 --save
INFO:root:loading FCNResNet101 from pretrained/model_segmentation_skin_30.pth
Traceback (most recent call last):
  File "evaluate_images.py", line 58, in <module>
    model = load_model(models[args.model_type], torch.load(args.model))
  File "C:\Users\raghaver\Anaconda3\envs\semantic_segmentation\lib\site-packages\torch\serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\raghaver\Anaconda3\envs\semantic_segmentation\lib\site-packages\torch\serialization.py", line 763, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by WillBrennan** [comment]
This is usually because of git-lfs. Check the model weights have been correctly downloaded.
