### ISSUE TITLE
Semantic Segmentation Tool

### ISSUE THREAD

**Issue by SaharGezer** [WillBrennan/SemanticSegmentation#12]
I want to train the net on my own datasets but I do not know which tool I need to use in order to tag the datasets.

Can you give me the name of the tool?

Thanks

**Comment by WillBrennan** [comment]
Hey; 

In the readme there's a section on [New Projects](https://github.com/WillBrennan/SemanticSegmentation#training-new-projects). It explains how to use an opensource tool called "labelme" to annotate the images. Its in the "semantic_segmentation" conda enviroment created in [Getting Started](https://github.com/WillBrennan/SemanticSegmentation#getting-started) section of the readme.
