### ISSUE TITLE
CPU

### ISSUE THREAD

**Issue by luantunez** [WillBrennan/SemanticSegmentation#15]
Hello, I was trying to use your model on skin segmentation in a CPU, but I am not being able to predict over an image. Is that possible? Would you help me with the code modifications, please?
Thank you, Lucia

**Comment by WillBrennan** [comment]
There's three places where `.cuda()` or `device='cuda'` is used. These need to be a global variable somewhere; that defines what device to use. 

```cpp
device = 'cuda' if torch.cuda.is_available() else 'cpu'
```
I need to make this change to the two other pytorch projects as well. I'll look at doing it in the next week.

**Comment by luantunez** [comment]
Thank you for your response. I was able to make the predictions with your modifications. I am not getting the same results though, but a much smaller threshold is needed and not even then I get a good segmentation. 
Do you know why should that be?

**Comment by luantunez** [comment]
BTW, which are these three places? I am only seeing two and getting the runtime error though:

device = torch.device("cpu")

being used in: 
model = load_model(models[model_type], torch.load(model_ckpt, map_location=device))
image = image.to(device).unsqueeze(0)

**Comment by WillBrennan** [comment]
There was also a call to `model.cuda().eval()` which needed to be changed. You can see it in the PR #17
