### ISSUE TITLE
Cannot launch "labelme"

### ISSUE THREAD

**Issue by vjdaemp** [WillBrennan/SemanticSegmentation#19]
I would like to add training data to the model, but am unable to launch 'labelme' from environment:

```
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)
```
Am I missing a dependency? FYI - I am running Ubuntu 20.04.

**Comment by WillBrennan** [comment]
Check you’re running with python 3 and that Qt is installed. The easiest way to install Qt is with conda using ‘conda install pyqt’. 

If that doesn’t work you can download a standalone version of labelme from their GitHub repo
