### ISSUE TITLE
Input Shape

### ISSUE THREAD

**Issue by vjdaemp** [WillBrennan/SemanticSegmentation#20]
@WillBrennan  What is the input shape of the model tensor for model_segmentation_skin_30.pth? [1,3,480,480] ?

**Comment by WillBrennan** [comment]
These models are fully convolutions, it can have any input size as long as the width and height are visible by 32. For example 480 = 15 * 32. 

This doesn’t mean that the model is scale invariant however. It expects people to be between 200px and 400px in the image. 

You could have a HD scene of a crowd but as long as people are the right size it’ll work. 

Hope this helps!

**Comment by vjdaemp** [comment]
Hi @WillBrennan , Thanks for the explanation.

I am trying to use Amazon SageMaker to convert the pytorch model to coreML model so that it can run on iOS environment (See article: https://aws.amazon.com/blogs/machine-learning/optimizing-ml-models-for-ios-and-macos-devices-with-amazon-sagemaker-neo-and-core-ml/)

One of the required parameters to enter is "Data Input Configuration" so that the tool knows what the shape of the data matrix is. This data is specified to the tool in following format: {"data":[1,3,488,388]}

The Amazon SageMaker has been failing to convert, and I believe it is because I am specifying the incorrect shape.
