### ISSUE TITLE
How did I get SS to show black and white skin mask

### ISSUE THREAD

**Issue by LinuxBeaver** [WillBrennan/SemanticSegmentation#26]
I need Semantic Segmentation to show a black and white skin mask so I can feed it to Gimp as a layer mask for skin. How do I do this? At this point I have to manually create a skin mask in Gimp.

![image](https://user-images.githubusercontent.com/78667207/163685122-bb0a4626-3d33-4b9f-b383-61711779ab3e.png)

**Comment by WillBrennan** [comment]
This can be done using the `category_mask`; this is not saved currently.

https://github.com/WillBrennan/SemanticSegmentation/blob/014ea13fa9f35bef08e29b50d01c64893943e899/semantic_segmentation/visualisation.py#L35
