### ISSUE TITLE
Tranfer learning

### ISSUE THREAD

**Issue by saskra** [WillBrennan/SemanticSegmentation#27]
Unfortunately, skin segmentation works very poorly on my own smartphone photos. You wouldn't happen to have a short tutorial on how I could use my own ground truth masks on these images to improve your model via transfer learning/fine tuning? Do you have examples of the masks used so I can generate mine in the same format (I use a different program than labelme)? Did you create these masks yourself, or are they part of the COCO dataset? 

Or is there just some pre-processing of the images that I should have done?

**Comment by WillBrennan** [comment]
Hey! The model was trained on images from COCO. That dataset uses VGA images (640x480), and this model will expect people to be around 100px ~ 500px tall in the images.
