### ISSUE TITLE
Working on Colab - import an image and test skin model

### ISSUE THREAD

**Issue by gg4u** [WillBrennan/SemanticSegmentation#4]
Hi Will,

thank you so much for sharing your work, i would like to adopt for a pilot project using Colab environment.

First thing I would like to replicate demo you shown, could you please help in addressing the issues I found? I'm using Colab.

(I also issues and solutions not relevant to your library for other people who may experience same troubles)

**Could not activate working env in Colab** 
See: 
- https://datascience.stackexchange.com/questions/75948/how-to-setup-and-run-conda-on-- google-colab/75979?noredirect=1#comment81199_75979
- https://stackoverflow.com/questions/62610289/conda-activate-and-conda-init-fail-to-work-in-colab-as-per-june-2020

I solved it by making explicit the dependencies on yml:
```
!conda install -y -c pytorch -c conda-forge  pytorch==1.5 python==3.7.5 pip pytorch==1.5 torchvision==0.6.0 cudatoolkit=10.1 numpy==1.16.3
!pip install pytorch-ignite opencv-python pycocotools tensorboard albumentations yapf pytest labelme ignite 
```

However cannot run the library :

```
from semantic_segmentation import models
from semantic_segmentation import load_model
from semantic_segmentation import draw_results
```

because `ignite` module cannot be found.

I tried any of the following:

```
!conda install ignite -c pytorch -y
!pip install pytorch-ignite --upgrade
!pip install git+https://github.com/pytorch/ignite
```
But all failed to even find the module `ignite` (nomodule found).

I tried to install it from repo:

```
!git clone https://github.com/pytorch/ignite
python ./ignite/setup.py install

```
In this case ignite is installed but cannot load modules as expected:

```
from ignite import engine
ImportError: cannot import name 'engine'
```

Could you help to get your project set properly up ?

**Locating the dataset**

You mentioned you used a db of about 150 labelled images.
Where can I find it ?

**Comment by WillBrennan** [comment]
Hi; 

its nice and simple, here's an [example on colab](https://colab.research.google.com/drive/1AqBAqC9WbdC4GTDgrGNtzELXr0_ASv5p?usp=sharing). Its importing torch successfully at the end and has the correct version ect. 

The datasets for skin and pizza are closed source; I paid for them to be annotated so I'm not super eager to release them. The projects designed to let people train on their own labeme datasets. If you find failure cases for your use case, feel free to annotate them and send them over, I'll train a new model.
