### ISSUE TITLE
Invalid syntax "def find_files(dir_path: pathlib.Path, file_exts):" 

### ISSUE THREAD

**Issue by alberto-arletti** [WillBrennan/SemanticSegmentation#5]
Hi, 
I am trying to execute the evaluate_images.py file but it returns this error. 
The semicolon in the function arguments definition returns an invalid syntax error. 
Which version of Python are you using for this repo? 
Best Regards

**Comment by WillBrennan** [comment]
I suspect it’s complaining about the types. You need to use the latest version of python, python 3.8
