### ISSUE TITLE
Working with high resolution images

### ISSUE THREAD

**Issue by cpatrickalves** [WillBrennan/SemanticSegmentation#6]
Hi Will, 

Thanks for sharing this awesome project.
So, I am trying to run this with high-resolution images and the results were not good.

Here are some examples
Input images: 
![14](https://user-images.githubusercontent.com/22003608/96908019-6fd52900-1472-11eb-8af7-929fd99ba9f4.jpg)
![15](https://user-images.githubusercontent.com/22003608/96908025-7368b000-1472-11eb-8f6b-ab57bae777bc.jpg)

These are the results:
![mask_skin_14](https://user-images.githubusercontent.com/22003608/96908100-8da28e00-1472-11eb-98c9-d8283309bdcd.jpg)
![mask_skin_15](https://user-images.githubusercontent.com/22003608/96908108-9004e800-1472-11eb-9caa-8140ba383413.jpg)

Then, I’ve reduce the obama image to 1024x1024 (previous was 3000x2284) and the white guy reduce from 1300x1241 to 512x512.
New results:

![mask_skin_15_1024](https://user-images.githubusercontent.com/22003608/96908257-bf1b5980-1472-11eb-9adb-a3dca580cb92.jpg)
![mask_skin_14-512x](https://user-images.githubusercontent.com/22003608/96908218-b1fe6a80-1472-11eb-9d59-0c330f792424.jpg)

I was wondering if this is happen beacuse the model was trained with lower resolution images, is that right?

**Comment by WillBrennan** [comment]
Hey! 

It's just where it's trained on lower resolution images. If you need the higher resolutions I'd suggest training it on your dataset with larger faces.

**Comment by cpatrickalves** [comment]
Got it!

Thanks
