### ISSUE TITLE
作者你好，你肤色检测只用了150张图片训练，就能得到理想的效果？

### ISSUE THREAD

**Issue by ersanliqiao** [WillBrennan/SemanticSegmentation#7]
作者你好，你肤色检测只用了150张图片训练，就能得到理想的效果？

**Comment by ersanliqiao** [comment]
How can you release your code and pretrained weight just trained on 150 images, the results is really bad!!!

**Comment by ersanliqiao** [comment]
Which I said is the skin segmentation model!!

**Comment by WillBrennan** [comment]
Hey - I'd suggest trying out the accurate model first and checking your input resolution. I've managed to get decent results with that. Please can you post the images you're trying to run on.

**Comment by ersanliqiao** [comment]
OK, I will check it again, thank you!

**Comment by ersanliqiao** [comment]
I want to know which resolution did you train your skin model?

**Comment by WillBrennan** [comment]
The model is trained on 480x480 crops; and people take up the majority of those images. If you resize your images to VGA (640x480) it should perform well.

https://github.com/WillBrennan/SemanticSegmentation/blob/master/semantic_segmentation/dataset.py#L50

**Comment by ersanliqiao** [comment]
OK, thank you very much!!!
