### ISSUE TITLE
Running out of memory

### ISSUE THREAD

**Issue by alexbarnadas** [WillBrennan/SemanticSegmentation#8]
Sorry to interrupt your peace, I've been trying to run your code to train my own model on skin detection, but it always says it runs out of memory, I've checked out on the internet and all answers I get is that I should clean the data in each iteration or things like that.
When I try to use the pretrained models it also runs out of memory if the picture is like more than 1Mb.

The thing is that I don't think your code is not working, so there must be something I'm doing wrong. Do you have any idea on what could it be?

I have 4Gb of GPU and 12 of ram, so actually memory shouldn't be a problem I think. I'm running it in Windows10 with a GPU nvidia gtx 1050ti, that I bought just to run your code :'(

**Comment by WillBrennan** [comment]
Hi Alex; 

The default model is based on ResNet-101 which is a huge model. I've got a GPU with 8GB memory and I can just do a batch-size of two. I'd suggest trying to train with the real-time model, BiSeNet-V2, and see if that works on your machine? As BiSeNet-V2 is a tiny model you can probably increase the batch-size but you might get generalisation errors.

If that works then it'd be worth adding a ResNet-50 FCN model to this project, if you make a PR I'll be happy to review and merge it.

**Comment by WillBrennan** [comment]
Just checked on my machine; 

FCNResNet101 - batch-size 2 - 5990MB of GPU 
FCNResNet101 - batch-size 1 - 4032MB of GPU 
BiSeNetV2 - batch-size 2 - 1960MB of GPU

. Turns out FCN ResNet-50 in torchvision isn't pretrained, so it'd need a lot more data to train unfortunately.
